### ISSUE TITLE
Update Belgian occurrence indicators based on corrected cubes

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#128]
Run occurrence based indicators on corrected cubes:
- Occurrence cubes for non-native taxa in Belgium and Europe: https://zenodo.org/records/10527772
- Occurrence cubes at species level for European countries: https://zenodo.org/records/10528506

This means running all Rmds in `./src` from [5](https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd) to [12](https://github.com/trias-project/indicators/blob/main/src/12_taxonomic_distribution_emerging_species.Rmd).

**Comment by soriadelva** [comment]
Update: the links to the corrected cubes on zenodo have been added where necessary. However, two errors occurred

- [ ] In script 09_define_overlay_grid_belgium_with_protected_areas.Rmd: The download of the Natura2000_end2019_Shapefile fails (a folder is created on the local computer but remains empty).  It goes wrong somewhere in the following lines: https://github.com/trias-project/indicators/blob/9e9668d5b4b66cd67777c271db4d9f052dd5134a/src/09_define_overlay_grid_belgium_with_protected_areas.Rmd#L61-L71

- [ ] In script 07_occurrence_indicators_modelling.Rmd the following error occurs when running the trias::apply_gam function:
`Error in `map2()`:
ℹ In index: 6.
Caused by error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `smooth` doesn't exist.`
This same error has also appeared in another repo that uses the apply_gam function: see https://github.com/trias-project/trias/issues/113

**Comment by damianooldoni** [comment]
First problem solved via c6e5763

**Comment by soriadelva** [comment]
@damianooldoni I tried to rerun the 07_occurrence_indicators_modelling.Rmd script but still encountered the same error linked to the apply_gam function (column smooth doesn't exist). It has likely something to do with how I loaded the updated version of the trias package on my local computer (I fetched the main branch of trias-project/trias and did  "update from main" in Github Desktop for the current branch linked to issue #128 of trias-project/indicators). As that still gave an error, I updated the trias package on my local computer but that also didn't work. Do you know if I still need to do something else? Thanks in advance!

**Comment by damianooldoni** [comment]
Hi @soriadelva. The `trias` branch with the update was still not merged to `main`. That was indeed my task to do after your review. I have just merged to `main`. You could now via GitHub Desktop:
1. go to trias repository 
2. check you are on main branch
3. click on "fetch origin"
4. Pull the changes
5. Open tias RStudio project related to trias R package
6. Run `devtools::install()`
7. Close it
8. Open indicator R project or close it and open it again.
9. Run `library(trias)`
10. Check you have the right package version by running `devtools::session_info()`. If you see a line with `trias       * 2.1.0` it's ok.

So, in general, it's just a question of checking versions of a package. This is a nice example why it's important to apply versioning in package development 😄 

Please, don't hesitate to contact me here or via chat if something is not working or not clear.

**Comment by soriadelva** [comment]
> Hi @soriadelva. The `trias` branch with the update was still not merged to `main`. That was indeed my task to do after your review. I have just merged to `main`. You could now via GitHub Desktop:
> 
> 1. go to trias repository
> 2. check you are on main branch
> 3. click on "fetch origin"
> 4. Pull the changes
> 5. Open tias RStudio project related to trias R package
> 6. Run `devtools::install()`
> 7. Close it
> 8. Open indicator R project or close it and open it again.
> 9. Run `library(trias)`
> 10. Check you have the right package version by running `devtools::session_info()`. If you see a line with `trias       * 2.1.0` it's ok.
> 
> So, in general, it's just a question of checking versions of a package. This is a nice example why it's important to apply versioning in package development 😄
> 
> Please, don't hesitate to contact me here or via chat if something is not working or not clear.

Thanks @damianooldoni, this worked! I ran all scripts and knit the respective .Rmd files. Before I generate a Pull Request, do you want me to commit all the files that have been overwritten by the changes?

**Comment by damianooldoni** [comment]
Did you remember to delete all existent images before generating the new ones?

Yes, you can push the changes in some commits and then generate a Pull Request 👍  Thanks a lot.

**Comment by soriadelva** [comment]
> Did you remember to delete all existent images before generating the new ones?
> 
> Yes, you can push the changes in some commits and then generate a Pull Request 👍 Thanks a lot.

oh no, I didn't! 😓 I'll run it again!!
